swagger: '2.0'
info:
  title: Lead Service
  version: 9b3f21c
definitions: {}
paths:
  /lead:
    post:
      summary: Add a new lead
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              agentEmail:
                type: string
                example: agent@sideinc.com
              extraNotes:
                type: string
                example: extra notes
              lead:
                type: object
                properties:
                  email:
                    type: string
                    example: lead.test@sideinc.com
                  firstName:
                    type: string
                    example: Lead first name
                    description: First Name of the Lead
                  lastName:
                    type: string
                    example: Lead last name
                  message:
                    type: string
                    example: I would like to buy this property
                  phone:
                    type: string
                    example: '1234567890'
                  source:
                    type: string
                    example: website
                  type:
                    type: string
                    example: buyer
                    enum:
                      - buyer
                      - seller
                required:
                  - firstName
              property:
                type: object
                properties:
                  area:
                    type: string
                    example: 6000 sqft
                  baths:
                    type: string
                    example: '3'
                  beds:
                    type: string
                    example: '4'
                  city:
                    type: string
                    example: San Fransisco
                  country:
                    type: string
                    example: US
                    enum:
                      - US
                  fullAddress:
                    type: string
                    example: property address
                  lotSize:
                    type: string
                    example: '8000'
                  mlsId:
                    type: string
                    example: '1234567'
                  mlsName:
                    type: string
                    example: SFAR
                  price:
                    type: string
                    example: '5000000'
                  state:
                    type: string
                    example: California
                    enum:
                      - Alaska
                      - Alabama
                      - Arkansas
                      - American Samoa
                      - Arizona
                      - California
                      - Colorado
                      - Connecticut
                      - District of Columbia
                      - Delaware
                      - Florida
                      - Georgia
                      - Guam
                      - Hawaii
                      - Iowa
                      - Idaho
                      - Illinois
                      - Indiana
                      - Kansas
                      - Kentucky
                      - Louisiana
                      - Massachusetts
                      - Maryland
                      - Maine
                      - Michigan
                      - Minnesota
                      - Missouri
                      - Mississippi
                      - Montana
                      - North Carolina
                      - ' North Dakota'
                      - Nebraska
                      - New Hampshire
                      - New Jersey
                      - New Mexico
                      - Nevada
                      - New York
                      - Ohio
                      - Oklahoma
                      - Oregon
                      - Pennsylvania
                      - Puerto Rico
                      - Rhode Island
                      - South Carolina
                      - South Dakota
                      - Tennessee
                      - Texas
                      - Utah
                      - Virginia
                      - Virgin Islands
                      - Vermont
                      - Washington
                      - Wisconsin
                      - West Virginia
                      - Wyoming
                  street:
                    type: string
                    example: property street
                  type:
                    type: string
                    example: Single Family Home
                  url:
                    type: string
                    example: www.sideinchomes.com/sanfransisco/propertystreet
                  zipCode:
                    type: string
                    example: '94016'
            required:
              - lead
      responses:
        '200':
          description: Created
          schema:
            type: object
            properties:
              success:
                type: string
            example:
              success: 'true'
            description: Created
        '400':
          description: Failed to add a new lead
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: 'Error: Failed to add a new lead'
            description: Failed to add a new lead
        '401':
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: Unauthorized
            description: Unauthorized
  /webhooks:
    post:
      summary: Subscribe to hook
      parameters:
        - name: body
          in: body
          schema:
            type: object
            required:
              - events
              - hookUrl
            additionalProperties: false
            properties:
              hookUrl:
                type: string
                example: https://example.com/hooksresponse
              secret:
                type: object
                properties:
                  key:
                    type: string
                    example: key
                  value:
                    type: string
                    example: value
              events:
                type: array
                items:
                  type: string
                example:
                  - lead.create
      responses:
        '200':
          description: Created a subscription
          schema:
            type: object
            description: Created a subscription
            additionalProperties: false
            properties:
              id:
                type: string
                example: HSKSK777666SNSNSS
        '400':
          description: Failed to add a new subscription
          schema:
            type: object
            description: Failed to add a new subscription
            properties:
              message:
                type: string
            example:
              message: body should have required property 'hookUrl'
        '401':
          description: Unauthorized
          schema:
            type: object
            description: Unauthorized
            properties:
              message:
                type: string
                example: Unauthorized
        '403':
          description: Agent subscription max limit reached
          schema:
            type: object
            description: Agent subscription max limit reached
            properties:
              message:
                type: string
                example: Agent subscription max limit reached
  /webhooks/{id}:
    delete:
      parameters:
        - type: string
          minLength: 1
          description: webhook id that needs to be removed
          required: true
          in: path
          name: id
      responses:
        '200':
          description: Subscription Deleted
          schema:
            description: Subscription Deleted
            type: object
            properties:
              message:
                type: string
                example: Successfully removed the subscription
        '400':
          description: Failed to delete the subscription
          schema:
            description: Failed to delete the subscription
            type: object
            properties:
              message:
                type: string
                example: params.id should NOT be shorter than 1 characters
        '401':
          description: Unauthorized
          schema:
            description: Unauthorized
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
        '404':
          description: hookId not found
          schema:
            description: hookId not found
            type: object
            properties:
              message:
                type: string
                example: Hook ID not found
  /auth/health:
    get:
      responses:
        '200':
          description: Default Response
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: success
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
